#! SHARED

test: &test
  - task: install-deps
    image: node
    file: src/ci/partials/install-deps.yml

  - in_parallel:
      - task: test
        image: node
        file: src/ci/partials/test.yml

      - task: lint
        image: node
        file: src/ci/partials/lint.yml

#!  JOBS

jobs:
  - name: test
    plan:
      - get: src
        resource: pr
        trigger: true
        version: every
      - put: #@ pr_hook("pending", "test")

      - get: node
      - get: general-task

      - do: *test

    on_failure: #@ pr_hook("failure", "test")
    on_success: #@ pr_hook("success", "test")

  - name: deploy
    plan:
      - get: src
        resource: src
        trigger: true
        passed: [set-pipeline]
        params: { depth: 1 }

      - get: node
      - get: general-task
      - get: pipeline-tasks

      - do: *test

      - task: deploy
        image: general-task
        file: src/ci/partials/deploy.yml
        params:
          _: #@ template.replace(data.values.env_cf_email)
          CF_APP_NAME: pages-mailer

        on_failure:
          try:
            task: cancel-deployment
            image: general-task
            file: pipeline-tasks/tasks/cancel-deployment.yml
            params:
              _: #@ template.replace(data.values.env_cf_email)
              CF_APP_NAME: pages-mailer

    on_failure: #@ slack_hook("failure", "deploy")
    on_success: #@ slack_hook("success", "deploy")

  - name: restage
    plan:
      - get: src
        resource: src
        passed: [set-pipeline]
        params: { depth: 1 }
      - get: general-task
      - get: pipeline-tasks
      - get: nightly
        trigger: true

      - task: restage
        image: general-task
        file: pipeline-tasks/tasks/restage.yml
        params:
          _: #@ template.replace(data.values.env_cf_email)
          CF_APP_NAME: pages-mailer

  - name: set-pipeline
    serial: true
    plan:
      - get: src
        params: { depth: 1 }
        trigger: true
      - get: pipeline-tasks
      - get: general-task
      - task: init
        image: general-task
        file: pipeline-tasks/tasks/init.yml
        params:
          PIPELINE_YML: src/ci/pipeline.yml
      - set_pipeline: mailer
        file: compiled/set-pipeline.yml

#!  RESOURCES

resources:
  - name: pr
    type: pull-request
    check_every: 1m
    source:
      repository: cloud-gov/pages-mailer
      access_token: ((gh-access-token))
      base_branch: main
      disable_forks: true
      ignore_drafts: false

  - name: src
    type: git
    icon: github
    source:
      uri: https://github.com/cloud-gov/pages-mailer
      branch: main
      commit_verification_keys: ((cloud-gov-pages-gpg-keys))

  - name: nightly
    type: time
    source:
      start: 12:00 AM
      stop: 1:00 AM
      location: America/New_York

  - name: pipeline-tasks
  - name: slack
  - name: node
  - name: general-task

#!  RESOURCE TYPES

resource_types:
  - name: git
  - name: pull-request
  - name: slack-notification
  - name: time
  - name: registry-image
