############################
#  SHARED

email-cf: &email-cf
  CF_API: https://api.fr.cloud.gov
  CF_USERNAME: ((email-cf-username))
  CF_PASSWORD: ((email-cf-password))
  CF_ORG: gsa-18f-federalist
  CF_SPACE: email
  CF_APP_NAME: pages-mailer
  CF_STACK: cflinuxfs4

node-image: &node-image
  platform: linux
  image_resource:
    type: registry-image
    source:
      aws_access_key_id: ((ecr-aws-key))
      aws_secret_access_key: ((ecr-aws-secret))
      repository: pages-node-v20
      aws_region: us-gov-west-1
      tag: latest

cf-image: &cf-image
  platform: linux
  image_resource:
    type: registry-image
    source:
      aws_access_key_id: ((ecr-aws-key))
      aws_secret_access_key: ((ecr-aws-secret))
      repository: general-task
      aws_region: us-gov-west-1
      tag: latest

test: &test
- task: install-deps
  config:
    <<: *node-image
    inputs: [name: src]
    outputs: [name: src]
    run:
      dir: src
      path: bash
      args: [-c, npm ci]

- in_parallel:
  - task: test
    config:
      <<: *node-image
      inputs: [name: src]
      outputs: [name: src]
      run:
        dir: src
        path: bash
        args: [-c, npm test]

  - task: lint
    config:
      <<: *node-image
      inputs: [name: src]
      outputs: [name: src]
      run:
        dir: src
        path: bash
        args: [-c, npm run lint]


############################
#  JOBS

jobs:

- name: test
  plan:
  - get: src
    resource: pr
    trigger: true
    version: every

  - put: src
    resource: pr
    params:
      path: src
      status: pending
      base_context: concourse
      context: test

  - do: *test

  on_failure:
    put: src
    resource: pr
    params:
      path: src
      status: failure
      base_context: concourse
      context: test

  on_success:
    put: src
    resource: pr
    params:
      path: src
      status: success
      base_context: concourse
      context: test

- name: deploy
  plan:
  - get: src
    resource: src
    trigger: true
    passed: [set-pipeline]
    params: {depth: 1}

  - do: *test

  - task: deploy
    config:
      <<: *cf-image
      inputs: [name: src]
      run:
        dir: src
        path: ci/tasks/deploy.sh
    params:
      <<: *email-cf

    on_failure:
      try:
        task: cancel-deployment
        config:
          <<: *cf-image
          inputs: [name: src]
          run:
            dir: src
            path: ci/tasks/cancel-deployment.sh
        params:
          <<: *email-cf

  on_failure:
    put: slack
    params:
      text: |
        :x: FAILED: pages mailer deployment
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

  on_success:
    put: slack
    params:
      text: |
        :white_check_mark: SUCCESS: Successfully deployed pages mailer
        <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
      channel: ((slack-channel))
      username: ((slack-username))
      icon_url: ((slack-icon-url))

- name: restage
  plan:
  - get: src
    resource: src
    passed: [set-pipeline]
    params: {depth: 1}
  - get: nightly
    trigger: true

  - task: restage
    config:
      inputs: [name: src]
      <<: *cf-image
      run:
        path: src/ci/tasks/restage.sh
    params:
      <<: *email-cf

- name: set-pipeline
  serial: true
  plan:
    - get: src
      resource: src
      params: {depth: 1}
      trigger: true
    - set_pipeline: mailer
      file: src/ci/pipeline.yml


############################
#  RESOURCES

resources:

  - name: pr
    type: pull-request
    check_every: 1m
    source:
      repository: cloud-gov/pages-mailer
      access_token: ((gh-access-token))
      base_branch: main
      disable_forks: true
      ignore_drafts: false

  - name: src
    type: git
    icon: github
    source:
      uri: https://github.com/cloud-gov/pages-mailer
      branch: main
      commit_verification_keys: ((cloud-gov-pages-gpg-keys))

  - name: nightly
    type: time
    source:
      start: 12:00 AM
      stop: 1:00 AM
      location: America/New_York

  - name: slack
    type: slack-notification
    source:
      url: ((slack-webhook-url))


############################
#  RESOURCE TYPES

resource_types:

  - name: pull-request
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: github-pr-resource
      aws_region: us-gov-west-1
      tag: latest

  - name: slack-notification
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: slack-notification-resource
      aws_region: us-gov-west-1
      tag: latest

  - name: time
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: time-resource
      aws_region: us-gov-west-1
      tag: latest

  - name: registry-image
    type: registry-image
    source:
      aws_access_key_id: ((ecr_aws_key))
      aws_secret_access_key: ((ecr_aws_secret))
      repository: registry-image-resource
      aws_region: us-gov-west-1
      tag: latest
